### model
model_name_or_path: ./saves/llama3-8b/full/sft
trust_remote_code: true

### method
finetuning_type: full

### dataset
task: mmlu_test
template: fewshot
lang: en
n_shot: 5

### output
save_dir: ./saves/llama3-8b/full/mmlu

### eval
batch_size: 4
